# Generated by Django 3.2.6 on 2021-08-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20210806_1256"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
